### ISSUE TITLE
Move to line with different indent than in current line?

### ISSUE THREAD

**Issue by fenuks** [jessekelighine/vindent.vim#1]
Currently plugin has option to jump to next line with same indent, and I think it would useful to jump to next line with *different* indent. That could be useful e.g. to jump out of long if in python code. 

Probably it would be useful to have few variants of this motion: `vindent_motion_different` (jump to line with different indent), `vindent_motion_decreased` (jump to line with decreased indent), `vindent_motion_increased` (jump to line with  increased indent).

Also side note, README mentions that plugin is implemented in less that 100 lines of vimscript, which seems to be (no longer?) case. Tokei raport:

```sh
$ tokei
===============================================================================
 Language            Files        Lines         Code     Comments       Blanks
===============================================================================
 Plain Text              1          287            0          233           54
 Vim script              2          149          131            9            9
-------------------------------------------------------------------------------
 Markdown                1          108            0           79           29
 |- TeX                  1           24           24            0            0
 (Total)                            132           24           79           29
===============================================================================
 Total                   4          544          131          321           92
===============================================================================
```

**Comment by jessekelighine** [comment]
I think jumping to different indentation levels is a good idea, I will implement those shortly.

And about the "less than 100 lines of vimscript"...  Yeah, It used to be true for the entire plugin.  Currently the core implementation in `autoload` is still under 100 lines, so I think it still counts?  But this probably wouldn't be true any more if the new features are added tho.

**Comment by fenuks** [comment]
> I think jumping to different indentation levels is a good idea, I will implement those shortly.

Thanks.

> And about the "less than 100 lines of vimscript"... Yeah, It used to be true for the entire plugin. Currently the core implementation in `autoload` is still under 100 lines, so I think it still counts? But this probably wouldn't be true any more if the new features are added tho.

Well, It counts, but is arguably a bit vague. Not that it really matters.

**Comment by jessekelighine** [comment]
I published a new release (v2.0.0) with more vindent motions implemented.  Please check it out!

**Comment by fenuks** [comment]
Thank you very much, works beautifully. I've been using https://github.com/michaeljsmith/vim-indent-object, but now I'm definitely switching to your plugin.

I wonder whether `vindent_motion_same_*` shouldn't be customisable, though. Current behaviour is to jump to next line of the same level. I think sometimes more convenient would be to jump to next line with same indent, but if it is preceded with either empty line or line with different indent, that is to jump to next indent block, not line. For example :

```
line 1 # cursor is here
line 2

line 4  # vindent_motion_same_next would jump here
``` 

```
line 1 # cursor is here
line 2
    line 3
line 4 # vindent_motion_same_next would jump here
```

**Comment by jessekelighine** [comment]
Hm, I'll have to think about this one, although `vindent_motion_same_*` "could" to be context depedent, IMO motions shouldn't be context dependent.  But I believe your request will be possible after the next release (make vindent text objects more flexible), so stay tuned!

**Comment by fenuks** [comment]
Perhaps it should be completely separate motion instead. I understand your objections about context, it surely makes motion more complex, but I think there are at least few ones that work this way, for example <kbd>%</kbd>. 

My rationale is that in interactive use, when I see that next line has same indent, it will be probably easier to type <kbd>j</kbd> (than vindent mapping that is unlikely to be mapped to just one key) to achieve similar effect. Maybe in things like macros, or complex mappings, current behaviour can be useful, though.

**Comment by jessekelighine** [comment]
I made a new release (v2.1.0) that contains a (several actually) new "block" motion, which navigates by "text blocks" with same indentations.  I believe what you need is the `g:vindent_blockmotion_OO` mapping, but also try out the other favours of the new block motion.  Enjoy and report back if you find any bugs! (I haven't test the new motions thoroughly)

**Comment by fenuks** [comment]
Thank you again! Set of new block motions is very thorough. Indeed `vindent_blockmotion_00` fits my needs in 100%. I've been playing a while in few files (my large init.vim, some large yaml files), and so far, I haven't spotted any problems. I plan to use it on daily matter, so if I find any issues, I'll let you know. Thank you again for being very responsive and open to suggestions. :-)
