### ISSUE TITLE
Variable name conflicts with existing function: Find

### ISSUE THREAD

**Issue by farzadmf** [jessekelighine/vindent.vim#2]
Hi, I had your plugin in my to-try things, and finally I decided to give it a shot

I was using `vim-indent-object`, specifically for Python files, but your plugin seems to have more features.

So, I installed the plugin using `vimplug` and add the "recommended" settings from the [`README`](https://github.com/jessekelighine/vindent.vim#usage-and-quick-start), however, when I do motions, for example, `vii` in a Python file, I get an error:
```
Error detected while processing function vindent#Object:
line    2:
E705: Variable name conflicts with existing function: Find
```

I _think_ it still visual selects properly, any chance we can figure out what's happening?

**Comment by jessekelighine** [comment]
Thank you for the issue.  I believe the reason is that even as a local function the name `Find` is way too generic, so I renamed some functions to avoid name collisions in the latest commit eeb5dc57ed45938cabcbdd608c97088f55b94e19.  Please check it out!

**Comment by farzadmf** [comment]
Nice, thank you for the quick response. Updated to latest and that issue is gone.

I think I'll have more questions about the bindings (once I familiarize myself with the documentation and other things), and I think I'll get back to you about those at some point 🙂
