### ISSUE TITLE
Mappings do not work [in vim 8.2] due to blocked remappings

### ISSUE THREAD

**Issue by rolicot** [jessekelighine/vindent.vim#4]
None of the keyboard mappings work due to the fact that the remapping for `<Plug>whatever` is forbidden by using e.g. `:nnoremap` instead of `:map` etc. By definition, the "`nore`" in mapping forbids remapping of the right-hand side of mapping, but it is supposed to be remapped by a second mapping that calls the actual function.

Changing `noremap` to `map`, `xnoremap` to `xmap` and `onoremap` to `omap` in all cases where `<Plug>*` is on the right hand side in `plugin/vindent.vim` fixes the problem.

**Comment by jessekelighine** [comment]
Thank you for pointing it out.  I found that Neovim's and Vim's `noremap` behave differently when `<Plug>` is present on the right-hand side.  I updated `plugin/vindent.vim` to make the mappings recursive.

**Comment by rolicot** [comment]
I did suspect that there was a difference between Neovim and Vim, otherwise it would get noticed. Thanks for a quick fix.

P.S.: I forgot to quote `<Plug>` in my original post and it got swallowed as markup, so it didn't make make much sense then.
