### ISSUE TITLE
jump table after

### ISSUE THREAD

**Issue by zig5000** [jessekelighine/vindent.vim#5]
Hi i installed your plugin
it works fine.

but when I use motion to next\prev indent block
my jump list do not change
and when i press Crtl-O after motion, I will motion to unexpected postion

for example, when I use targets.vim plugin
I press
vin"  - and  my cursor moved to last postion in text-object
i press <esc> to go in normal mode
and after I press Ctrl-O and my cursor move to previous position

**Comment by jessekelighine** [comment]
Yeah, `vindent.vim` motions wouldn't change the jump list.  I thought it wouldn't be necessary (but I can consider adding it).  As to why `ctrl-o` produces unexpected results, I do not know.  Try to use `:clearjumps` to clear the jump list, then try to reproduce the problem.

**Comment by zig5000** [comment]
Hi, thanks for your answer.

I will happy if your plugin will have "change jumplist" functionality.

About "unexprected ctrl-o results", I mean "ctrl-o"  not jump to my previous place, but jump to pre-previously.
It's normaly if your plugin doesn't change jumplist.

**Comment by jessekelighine** [comment]
I published a new release that contains the requested feature.  Simply put `let g:vindent_jumps = 1` in your `.vimrc` and you should be set.  The fix is quite simple so I have not tested this extensively, but do inform me if you encounter any problems.

**Comment by zig5000** [comment]
Great!
I am happy
